title: Resume - Sree Sai Nandini Gundraju
description: Mahal, Andhra Pradesh, India | sreesainandinigundraju@gmail.com | +91 9390546597
social links:
  - linkedin: https://www.linkedin.com/in/g-sree-sai-nandini/
  - github: https://www.github.com/Sree2011/
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-pdf


relative_links:
  enabled: true
  collections: true
include:
 - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

remote_theme: pages-themes/cayman@v0.2.0

#theme: minimal-mistakes-jekyll
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
